language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
    - python setup.py install
    - pip install coveralls
script:
    - coverage run --source=nagisa setup.py test
after_success:
    - coveralls
