os: Visual Studio 2015

branches:
  only:
    - master
    - develop

build: off

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe setup.py install"

test_script:
  - "%PYTHON%\\python.exe setup.py test"
